spring.application.name=pharmacie-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/pharmacie_db
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

groq.api.key=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
groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.model=llama-3.1-8b-instant

# Clé secrète JWT ? minimum 32 caractères
# Clé secrète JWT générée de manière sécurisée (Hexadécimal 64 caractères = 32 octets)
jwt.secret=7f8a9b3c4d5e6f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

cors.allowed-origins=http://localhost:4200

server.port=8080